# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hitchhiker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hitchhiker.proto\x12\nhitchhiker\x1a\x1bgoogle/protobuf/empty.proto\"D\n\x04\x46ile\x12\x0e\n\x06\x66ileid\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04\x62lob\x18\x04 \x01(\x0c\"\x16\n\x08SourceId\x12\n\n\x02id\x18\x01 \x01(\t\">\n\x13GetDownloadsRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x15\n\rdestinationId\x18\x02 \x01(\t\"+\n\x08\x46ileList\x12\x1f\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x10.hitchhiker.File\"H\n\x13\x44ownloadFileRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x1f\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x10.hitchhiker.File\"`\n\x14MarkDeliveredRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x15\n\rdestinationId\x18\x02 \x01(\t\x12\x1f\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x10.hitchhiker.File2\xa6\x02\n\x10HitchhikerSource\x12;\n\x0bGetSourceId\x12\x16.google.protobuf.Empty\x1a\x14.hitchhiker.SourceId\x12\x45\n\x0cGetDownloads\x12\x1f.hitchhiker.GetDownloadsRequest\x1a\x14.hitchhiker.FileList\x12\x43\n\x0c\x44ownloadFile\x12\x1f.hitchhiker.DownloadFileRequest\x1a\x10.hitchhiker.File0\x01\x12I\n\rMarkDelivered\x12 .hitchhiker.MarkDeliveredRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hitchhiker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILE']._serialized_start=61
  _globals['_FILE']._serialized_end=129
  _globals['_SOURCEID']._serialized_start=131
  _globals['_SOURCEID']._serialized_end=153
  _globals['_GETDOWNLOADSREQUEST']._serialized_start=155
  _globals['_GETDOWNLOADSREQUEST']._serialized_end=217
  _globals['_FILELIST']._serialized_start=219
  _globals['_FILELIST']._serialized_end=262
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=264
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=336
  _globals['_MARKDELIVEREDREQUEST']._serialized_start=338
  _globals['_MARKDELIVEREDREQUEST']._serialized_end=434
  _globals['_HITCHHIKERSOURCE']._serialized_start=437
  _globals['_HITCHHIKERSOURCE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
